version: "3.2"

services:
  proxy:
    image: nginx:1.15
    ports:
      - '80:80'
      - '443:443'
    environment:
      - NGINX_HOST=sukill.zz.am
      - NGINX_PORT=80
  db:
    image: postgres:9.3
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1q2w3e4r5t
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      - atlassian

  confluence:
    image: sukill/confluence
    volumes:
        - confluence_home:/var/atlassian/application-data/confluence
        - confluence_opt:/opt
    ports:
      - "8090-8091:8090-8091"
    environment:
      - 'CATALINA_CONNECTOR_PROXYNAME='
      - 'CATALINA_CONNECTOR_PROXYPORT='
    depends_on:
      - db
    networks:
      - atlassian

  jira:
    image: sukill/jira-software
    volumes:
      - jira_home:/var/atlassian/jira
      - jira_opt:/opt
 
    ports:
      - '8080:8080'
#    environment:      
#      - 'CATALINA_CONNECTOR_PROXYNAME=jira.sukill.zz.am'
#      - 'CATALINA_CONNECTOR_PROXYPORT=8080'
    depends_on:
      - db
    networks:
      - atlassian

volumes:
  postgres_data:
  confluence_home:
  confluence_opt:
  jira_home:
  jira_opt:

networks:
  atlassian:
