version: "3.2"

services:
  proxy:
    image: nginx:1.15
    volumes:
      - ./cert:/etc/nginx/cert
      - ./nginx/conf.d:/etc/nginx/conf.d
      - nginx_conf:/etc/nginx
    ports:
      - '80:80'
      - '443:443'
    environment:
      - NGINX_HOST=[YOUR_DOMAIN]
      - NGINX_PORT=80
    links:
      - confluence
      - jira
    networks:
      - atlassian
  db:
    image: postgres:9.3
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=[YOUR_SECRET_PASSWORD]
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      - atlassian

  confluence:
    image: sukill/confluence
    volumes:
        - ./cert:/etc/cert
        - confluence_home:/var/atlassian/application-data/confluence
        - confluence_opt:/opt
    ports:
      - "8090-8091:8090-8091"
    environment:
      - 'CATALINA_CONNECTOR_PROXYNAME=[YOUR_PROXY_NAME]'
      - 'CATALINA_CONNECTOR_PROXYPORT=443'
      - 'CATALINA_CONNECTOR_SCHEME=https'
      - 'CATALINA_CONNECTOR_SECURE=true'
      - 'CATALINA_CONTEXT_PATH=/confluence'
      - 'CATALINA_CERT_LOCATION=/etc/cert/[PKCS12_KEY_FILE]'
      - 'CATALINA_KEYSTORE_PASS=[YOUR_KEYSTORE_PASS]'
      - 'CATALINA_KEY_ALIAS=letsencrypt'
    depends_on:
      - db
    networks:
      - atlassian

  jira:
   image: sukill/jira-software
   volumes:
     - ./cert:/etc/cert
     - jira_home:/var/atlassian/jira
     - jira_opt:/opt
   ports:
     - '8080:8080'
   environment:      
      - 'CATALINA_CONNECTOR_PROXYNAME=[YOUR_PROXY_NAME]'
      - 'CATALINA_CONNECTOR_PROXYPORT=443'
      - 'CATALINA_CONNECTOR_SCHEME=https'
      - 'CATALINA_CONNECTOR_SECURE=true'
      - 'CATALINA_CONTEXT_PATH=/jira'
      - 'CATALINA_CERT_LOCATION=/etc/cert/[PKCS12_KEY_FILE]'
      - 'CATALINA_KEYSTORE_PASS=[YOUR_KEYSTORE_PASS]'
      - 'CATALINA_KEY_ALIAS=letsencrypt'

   depends_on:
     - db
   networks:
     - atlassian

volumes:
  postgres_data:
  confluence_home:
  confluence_opt:
  jira_home:
  jira_opt:
  nginx_conf:

networks:
  atlassian:
