version: "3.2"

services:
  proxy:
    image: nginx:1.15
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - "/etc/letsencrypt/archive/sukill.zz.am:/certs"
    links:
      - confluence
      - jira
  
  db:
    image: postgres:9.3
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1q2w3e4r5t
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 1s
      retries: 10

  confluence:
    image: sukill/confluence
    volumes:
        - confluence_home:/var/atlassian/application-data/confluence
        - confluence_opt:/opt
    ports:
      - "8090-8091:8090-8091"
    environment:
      - 'CATALINA_CONNECTOR_PROXYNAME=sukill.zz.am'
      - 'CATALINA_CONNECTOR_PROXYPORT=443'
      - 'CATALINA_CONNECTOR_SCHEME=https'
      - 'CATALINA_CONNECTOR_SECURE=true'
      - 'CATALINA_CONTETXT_PATH=/confluence'
    depends_on:
      - db

  jira:
    image: sukill/jira-software
    volumes:
      - jira_home:/var/atlassian/jira
      - jira_opt:/opt
 
    ports:
      - '8080:8080'
    environment:      
      - 'X_PROXY_NAME=sukill.zz.am'
      - 'X_PROXY_PORT=443'
      - 'X_PROXY_SCHEME=https'
      - 'X_PATH=jira'
    depends_on:
      - db
volumes:
  postgres_data:
  confluence_home:
  confluence_opt:
  jira_home:
  jira_opt:

  
